import { db } from './firebase.js';
import { collection,getDocs,query,orderBy,doc,getDoc,setDoc,addDoc,updateDoc,serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import { getFunctions,httpsCallable } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-functions.js';
const $=id=>document.getElementById(id), moeda=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let contas=[], notas=[], boletos=[]; let contaOrigem=null;
const functions=getFunctions(); const sincronizarNfe=httpsCallable(functions,'sincronizarNfe');
function hoje(){return new Date().toISOString().slice(0,10)}
function statusConta(c){if(c.status==='PAGO')return 'PAGO'; if(c.vencimento && c.vencimento<hoje())return 'VENCIDO'; return 'PENDENTE'}
function data(v){if(!v)return '—'; const d=new Date(v); return isNaN(d)?String(v):d.toLocaleDateString('pt-BR')}
function renderResumo(){let aberto=0,vencendo=0,vencidas=0,pago=0; contas.forEach(c=>{const s=statusConta(c),v=Number(c.valor||0);if(s==='PAGO')pago+=v;else if(s==='VENCIDO')vencidas+=v;else {aberto+=v;if(c.vencimento){const diff=(new Date(c.vencimento+'T00:00:00')-new Date(hoje()+'T00:00:00'))/86400000;if(diff>=0&&diff<=7)vencendo+=v}}});$('aberto').textContent=moeda(aberto);$('vencendo').textContent=moeda(vencendo);$('vencidas').textContent=moeda(vencidas);$('pago').textContent=moeda(pago);$('ddaTotal').textContent=moeda(boletos.filter(b=>String(b.status||'PENDENTE')!=='PAGO').reduce((s,b)=>s+Number(b.valor||0),0))}
function renderContas(){const q=$('busca').value.toLowerCase().trim(),f=$('filtroStatus').value;const arr=contas.filter(c=>{const s=statusConta(c);return(f==='TODOS'||s===f)&&(!q||`${c.fornecedorNome||''} ${c.numeroNF||''} ${c.codigoBoleto||''} ${c.chaveNF||''}`.toLowerCase().includes(q))});$('lista').innerHTML=arr.length?`<table class="table"><thead><tr><th>Vencimento</th><th>Fornecedor</th><th>Origem</th><th>Documento</th><th>Valor</th><th>Status</th><th>Ação</th></tr></thead><tbody>${arr.map(c=>`<tr><td>${data(c.vencimento)}</td><td>${esc(c.fornecedorNome||'—')}<br><small>${esc(c.fornecedorCnpj||'')}</small></td><td>${esc(c.origem||'MANUAL')}</td><td>${esc(c.numeroNF||c.codigoBoleto||'—')}</td><td>${moeda(c.valor)}</td><td><span class="badge ${statusConta(c).toLowerCase()}">${statusConta(c)}</span></td><td>${statusConta(c)==='PAGO'?'—':`<button class="btn btn-outline btn-pagar" data-id="${c.id}">Marcar pago</button>`}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhuma conta encontrada.</div>';document.querySelectorAll('.btn-pagar').forEach(b=>b.onclick=()=>pagar(b.dataset.id))}
function renderNfe(){const q=$('buscaNfe').value.toLowerCase().trim(),f=$('statusNfe').value;const arr=notas.filter(n=>(f==='TODOS'||n.status===f)&&(!q||`${n.emitenteNome||''} ${n.emitenteCnpj||''} ${n.numero||''} ${n.chave||''}`.toLowerCase().includes(q)));$('listaNfe').innerHTML=arr.length?`<table class="table"><thead><tr><th>Emissão</th><th>Fornecedor</th><th>NF</th><th>Chave</th><th>Valor</th><th>Status</th><th>Ação</th></tr></thead><tbody>${arr.map(n=>`<tr><td>${data(n.emissao)}</td><td>${esc(n.emitenteNome||'—')}<br><small>${esc(n.emitenteCnpj||'')}</small></td><td>${esc(n.numero||'—')}</td><td><small>${esc(n.chave||'—')}</small></td><td>${moeda(n.valor)}</td><td><span class="badge ${(n.status||'NOVA').toLowerCase()}">${esc(n.status||'NOVA')}</span></td><td>${n.contaPagarId?'Conta a pagar criada':`<button class="btn btn-outline btn-nfe" data-id="${n.id}">Gerar conta</button>`}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhuma NF-e encontrada.</div>';document.querySelectorAll('.btn-nfe').forEach(b=>b.onclick=()=>gerarContaNfe(b.dataset.id))}
function renderDda(){const q=$('buscaDda').value.toLowerCase().trim();const arr=boletos.filter(b=>!q||`${b.fornecedorNome||''} ${b.documento||''} ${b.codigoBoleto||''} ${b.cnpj||''}`.toLowerCase().includes(q));$('listaDda').innerHTML=arr.length?`<table class="table"><thead><tr><th>Vencimento</th><th>Fornecedor</th><th>Banco</th><th>Documento</th><th>Valor</th><th>Status</th><th>Ação</th></tr></thead><tbody>${arr.map(b=>`<tr><td>${data(b.vencimento)}</td><td>${esc(b.fornecedorNome||'—')}<br><small>${esc(b.cnpj||'')}</small></td><td>${esc(b.banco||'—')}</td><td>${esc(b.documento||b.nossoNumero||'—')}</td><td>${moeda(b.valor)}</td><td><span class="badge ${String(b.status||'PENDENTE').toLowerCase()}">${esc(b.status||'PENDENTE')}</span></td><td>${b.contaPagarId?'Conta criada':`<button class="btn btn-outline btn-dda" data-id="${b.id}">Gerar conta</button>`}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum boleto DDA encontrado.</div>';document.querySelectorAll('.btn-dda').forEach(b=>b.onclick=()=>gerarContaDda(b.dataset.id))}
async function carregar(){const [a,b,c]=await Promise.all([getDocs(query(collection(db,'contasPagar'),orderBy('criadoEm','desc'))),getDocs(query(collection(db,'nfesRecebidas'),orderBy('emissao','desc'))),getDocs(query(collection(db,'boletosDda'),orderBy('vencimento','asc')))]);contas=a.docs.map(d=>({id:d.id,...d.data()}));notas=b.docs.map(d=>({id:d.id,...d.data()}));boletos=c.docs.map(d=>({id:d.id,...d.data()}));renderResumo();renderContas();renderNfe();renderDda()}
async function pagar(id){if(!confirm('Marcar esta conta como paga?'))return;await updateDoc(doc(db,'contasPagar',id),{status:'PAGO',pagoEm:serverTimestamp()});await carregar()}
function abrirConta(origem=null){contaOrigem=origem; $('tituloModal').textContent=origem?.titulo||'Registrar conta a pagar';$('fornecedorNome').value=origem?.fornecedorNome||'';$('tipo').value=origem?.tipo||'BOLETO';$('numeroNF').value=origem?.numeroNF||'';$('chaveNF').value=origem?.chaveNF||'';$('codigoBoleto').value=origem?.codigoBoleto||'';$('emissao').value=origem?.emissao||'';$('vencimento').value=origem?.vencimento||'';$('valor').value=origem?.valor??'';$('parcelas').value=origem?.parcelas||1;$('obs').value=origem?.obs||'';$('modalConta').classList.remove('hidden')}
async function salvarConta(){const v=Number($('valor').value||0);if(!$('fornecedorNome').value.trim()||!v||!$('vencimento').value){alert('Informe fornecedor, vencimento e valor.');return}const id=contaOrigem?.id||undefined;const dados={fornecedorNome:$('fornecedorNome').value.trim(),tipo:$('tipo').value,numeroNF:$('numeroNF').value.trim(),chaveNF:$('chaveNF').value.trim(),codigoBoleto:$('codigoBoleto').value.trim(),emissao:$('emissao').value||'',vencimento:$('vencimento').value,valor:v,parcelas:Number($('parcelas').value||1),obs:$('obs').value.trim(),status:'PENDENTE',origem:contaOrigem?.origem||'MANUAL',criadoEm:serverTimestamp()};if(id)await setDoc(doc(db,'contasPagar',id),dados,{merge:true});else await addDoc(collection(db,'contasPagar'),dados);if(contaOrigem?.collection)await updateDoc(doc(db,contaOrigem.collection,contaOrigem.id),{contaPagarId:id||'criada',status:'IMPORTADA'});$('modalConta').classList.add('hidden');await carregar()}
async function gerarContaNfe(id){const n=notas.find(x=>x.id===id);if(!n)return;abrirConta({titulo:'Conta a pagar — NF-e',fornecedorNome:n.emitenteNome,fornecedorCnpj:n.emitenteCnpj,tipo:'NOTA FISCAL',numeroNF:n.numero,chaveNF:n.chave,emissao:String(n.emissao||'').slice(0,10),vencimento:String(n.vencimento||n.emissao||'').slice(0,10),valor:n.valor,origem:'NF-E RECEBIDA',collection:'nfesRecebidas',id})}
async function gerarContaDda(id){const b=boletos.find(x=>x.id===id);if(!b)return;abrirConta({titulo:'Conta a pagar — DDA',fornecedorNome:b.fornecedorNome,tipo:'BOLETO',codigoBoleto:b.codigoBoleto,emissao:b.emissao,vencimento:b.vencimento,valor:b.valor,origem:'DDA',collection:'boletosDda',id})}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const sep=lines[0].includes(';')?';':',';const headers=lines[0].split(sep).map(x=>x.trim().toLowerCase().replace(/[^a-z0-9_]/g,''));return lines.slice(1).map(line=>{const vals=line.split(sep).map(x=>x.trim().replace(/^"|"$/g,''));const o={};headers.forEach((h,i)=>o[h]=vals[i]??'');return o})}
function mapDda(o){const pick=(...ks)=>{for(const k of ks)if(o[k]!=null&&o[k]!=='')return o[k];return ''};const valor=Number(String(pick('valor','valordocumento','valordoboleto')).replace(/\./g,'').replace(',','.'))||Number(pick('valor','valordocumento','valordoboleto'))||0;return{fornecedorNome:pick('fornecedor','beneficiario','nomebeneficiario','cedente'),cnpj:pick('cnpj','cnpjbeneficiario','documento'),banco:pick('banco','codigobanco'),nossoNumero:pick('nossonumero'),codigoBoleto:pick('linhadigitavel','codigobarras','codigo','barcode'),emissao:pick('emissao','dataemissao'),vencimento:pick('vencimento','datavencimento'),valor,status:'PENDENTE',origem:'DDA IMPORTADO',importadoEm:serverTimestamp()}}
async function importarArquivo(file){const text=await file.text();let arr=[];if(file.name.toLowerCase().endsWith('.json')){const j=JSON.parse(text);arr=Array.isArray(j)?j:(j.boletos||j.items||[])}else arr=parseCsv(text);if(!arr.length){alert('Nenhum registro encontrado no arquivo.');return}let count=0;for(const raw of arr){const b=mapDda(raw);if(!b.fornecedorNome||!b.vencimento||!b.valor)continue;await addDoc(collection(db,'boletosDda'),b);count++}alert(`${count} boleto(s) importado(s).`);await carregar()}
async function sincronizar(){const cfg=await getDoc(doc(db,'configuracoes','fiscal'));const c=cfg.exists()?cfg.data():{};if(!c.cnpj){$('modalFiscal').classList.remove('hidden');alert('Configure o CNPJ fiscal primeiro.');return}const file=$('certFiscal').files[0];const senha=$('senhaFiscal').value;if(!file||!senha){$('modalFiscal').classList.remove('hidden');alert('Para sincronizar agora, selecione o certificado A1 e informe a senha.');return}const buf=await file.arrayBuffer();let bin='';const bytes=new Uint8Array(buf);for(let i=0;i<bytes.length;i+=32768)bin+=String.fromCharCode(...bytes.subarray(i,i+32768));try{await sincronizarNfe({cnpj:c.cnpj,uf:c.uf||'GO',pfxBase64:btoa(bin),password:senha});$('senhaFiscal').value='';$('certFiscal').value='';await carregar();alert('NF-e sincronizadas com sucesso.');}catch(e){console.error(e);alert('Falha na sincronização: '+(e.message||e))}}
function tabs(){document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('view-'+t.dataset.view).classList.add('active')})}
$('novaConta').onclick=()=>abrirConta();$('fecharModal').onclick=()=>$('modalConta').classList.add('hidden');$('salvarConta').onclick=salvarConta;$('busca').oninput=renderContas;$('filtroStatus').onchange=renderContas;$('buscaNfe').oninput=renderNfe;$('statusNfe').onchange=renderNfe;$('buscaDda').oninput=renderDda;$('sincronizarNfe').onclick=()=>{$('modalFiscal').classList.remove('hidden')};$('fecharFiscal').onclick=()=>$('modalFiscal').classList.add('hidden');$('salvarFiscal').onclick=async()=>{const c=String($('cnpjFiscal').value||'').replace(/\D/g,'');if(c.length!==14){alert('CNPJ inválido.');return}await setDoc(doc(db,'configuracoes','fiscal'),{cnpj:c,uf:$('ufFiscal').value,atualizadoEm:serverTimestamp()},{merge:true});$('modalFiscal').classList.add('hidden');await sincronizar()};$('importarDda').onclick=()=>{$('view-dda').classList.add('active');document.querySelectorAll('.view').forEach(x=>x.id!=='view-dda'&&x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view==='dda'));$('arquivoDda').click()};$('selecionarDda').onclick=()=>$('arquivoDda').click();$('arquivoDda').onchange=e=>e.target.files[0]&&importarArquivo(e.target.files[0]);$('novoBoleto').onclick=()=>{$('modalDda').classList.remove('hidden')};$('fecharDda').onclick=()=>$('modalDda').classList.add('hidden');$('salvarDda').onclick=async()=>{const b={fornecedorNome:$('ddaFornecedor').value.trim(),cnpj:$('ddaCnpj').value.trim(),banco:$('ddaBanco').value.trim(),nossoNumero:$('ddaNossoNumero').value.trim(),codigoBoleto:$('ddaCodigo').value.trim(),emissao:$('ddaEmissao').value,vencimento:$('ddaVencimento').value,valor:Number($('ddaValor').value||0),documento:$('ddaDocumento').value.trim(),status:'PENDENTE',origem:'MANUAL',criadoEm:serverTimestamp()};if(!b.fornecedorNome||!b.vencimento||!b.valor){alert('Informe fornecedor, vencimento e valor.');return}await addDoc(collection(db,'boletosDda'),b);$('modalDda').classList.add('hidden');await carregar()};tabs();carregar().catch(e=>{console.error(e);$('lista').innerHTML='<div class="danger">Não foi possível carregar as contas. Verifique as permissões do Firestore.</div>'});
