const KEY='neoscale_delivery_config';
const SERVICE_DEFAULT='';
const columns=[['NOVO','Novos'],['PREPARO','Em preparo'],['PRONTO','Prontos'],['ENTREGA','Em entrega'],['CONCLUIDO','Concluídos']];
let orders=[];
const printedOrders=new Set();
const demo=[
{id:'IFD-1001',source:'iFood',customer:'Cliente iFood',status:'NOVO',items:['1x Prato executivo','1x Refrigerante'],total:42.90},
{id:'99F-2007',source:'99Food',customer:'Cliente 99Food',status:'PREPARO',items:['2x Marmita média'],total:38.00},
{id:'ANO-3012',source:'Anota AI',customer:'Cliente Anota',status:'PRONTO',items:['1x Combo família'],total:69.90}
];
function loadConfig(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function saveConfig(c){localStorage.setItem(KEY,JSON.stringify(c))}
function fmt(v){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function render(){const k=document.getElementById('kanban');k.innerHTML='';columns.forEach(([key,label])=>{const list=orders.filter(o=>o.status===key);const col=document.createElement('div');col.className='kanban-col';col.innerHTML=`<div class="kanban-title"><span>${label}</span><span>${list.length}</span></div>`;list.forEach(o=>{const next=key==='NOVO'?'PREPARO':key==='PREPARO'?'PRONTO':key==='PRONTO'?'ENTREGA':key==='ENTREGA'?'CONCLUIDO':null;const printBadge=printedOrders.has(o.id)?'<small class="print-ok">🖨️ Impresso</small>':''; const b=next?`<button data-id="${o.id}" data-next="${next}">${next==='PREPARO'?'Iniciar preparo':next==='PRONTO'?'Marcar pronto':next==='ENTREGA'?'Saiu para entrega':'Concluir'}</button>`:'';col.insertAdjacentHTML('beforeend',`<article class="order-card"><div class="order-top"><strong>${o.id}</strong><span class="source">${o.source}</span></div><p>${o.customer}</p><div class="order-items">${o.items.map(x=>`• ${typeof x==='string'?x:`${x.quantity||1}x ${x.name||'Item'}${x.notes?` — ${x.notes}`:''}`}`).join('<br>')}</div><div class="order-foot"><b>${fmt(o.total)}</b><span>${printBadge}</span>${b}</div></article>`) });k.appendChild(col)});updateCounts()}
function updateCounts(){const map={iFood:'ifoodCount','99Food':'food99Count','Anota AI':'anotaCount'};Object.entries(map).forEach(([s,id])=>document.getElementById(id).textContent=orders.filter(o=>o.source===s).length);document.getElementById('totalCount').textContent=orders.length}
async function sync(){const c=loadConfig();const log=document.getElementById('syncLog');if(c.mode==='live'&&c.serviceUrl){try{const r=await fetch(c.serviceUrl.replace(/\/$/,'')+'/api/delivery/orders');if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();const incoming=Array.isArray(data.orders)?data.orders:[]; const previousIds=new Set(orders.map(o=>o.id)); orders=incoming; if(c.mode==='live'){ for(const o of incoming){ if(!previousIds.has(o.id) && !printedOrders.has(o.id)){ try{await printKitchen(o); o.printedAt=new Date().toISOString();}catch(err){console.warn('Impressão automática falhou para',o.id,err.message);} } } } log.textContent=`Sincronizado com o serviço às ${new Date().toLocaleTimeString('pt-BR')}.`;setStatuses(true)}catch(e){log.textContent=`Falha ao sincronizar: ${e.message}. Exibindo modo local.`;orders=[...demo];setStatuses(false)}}else{orders=[...demo];log.textContent=`Modo demonstração local — ${new Date().toLocaleTimeString('pt-BR')}.`;setStatuses(false)}document.getElementById('lastSync').textContent=new Date().toLocaleString('pt-BR');render()}
function setStatuses(live){[['ifoodStatus','iFood'],['food99Status','99Food'],['anotaStatus','Anota AI']].forEach(([id,name])=>document.getElementById(id).textContent=live?'Conectado':'Modo demonstração')}
async function serviceRequest(path, options={}){const c=loadConfig();if(c.mode!=='live'||!c.serviceUrl)throw new Error('Serviço de Delivery não configurado.');const r=await fetch(c.serviceUrl.replace(/\/$/, '')+path,options);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||('HTTP '+r.status));return data;}
async function printKitchen(o){const data=await serviceRequest('/api/delivery/orders/'+encodeURIComponent(o.id)+'/print-kitchen',{method:'POST'});printedOrders.add(o.id);return data;}
async function pushStatus(o,next){return serviceRequest('/api/delivery/orders/'+encodeURIComponent(o.id)+'/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:next})});}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-next]');if(!b)return;const o=orders.find(x=>x.id===b.dataset.id);if(!o)return;const next=b.dataset.next;const c=loadConfig();b.disabled=true;try{if(next==='PREPARO'&&!printedOrders.has(o.id)&&c.mode==='live'){await printKitchen(o);o.printedAt=new Date().toISOString();}if(c.mode==='live'){const result=await pushStatus(o,next);if(result.order)o.status=result.order.status;}else{o.status=next;}render();}catch(err){alert('Não foi possível avançar o pedido.\n\n'+err.message);render();}finally{b.disabled=false;}});
const modal=document.getElementById('configModal');document.getElementById('btnConfig').onclick=()=>{const c=loadConfig();document.getElementById('serviceUrl').value=c.serviceUrl||SERVICE_DEFAULT;document.getElementById('operationMode').value=c.mode||'mock';modal.hidden=false};document.getElementById('closeConfig').onclick=()=>modal.hidden=true;document.getElementById('saveConfig').onclick=()=>{saveConfig({serviceUrl:document.getElementById('serviceUrl').value.trim(),mode:document.getElementById('operationMode').value});modal.hidden=true;sync()};document.getElementById('btnSync').onclick=sync;sync();
