import { db } from './firebase.js';
import { collection,getDocs,addDoc,updateDoc,deleteDoc,doc,serverTimestamp,query,orderBy } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const $=id=>document.getElementById(id), lista=$('listaFichas'), modal=$('modalFicha'), insumos=$('insumos'); let fichas=[], editId=null;
const money=v=>`R$ ${Number(v||0).toFixed(2).replace('.',',')}`; const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function linha(i={nome:'',quantidade:1,unidade:'kg',custoUnit:0}){const el=document.createElement('div');el.className='insumo-row';el.innerHTML=`<input class="ins-nome" placeholder="Nome do insumo" value="${esc(i.nome)}"><input class="ins-qtd" type="number" min="0" step="0.001" value="${Number(i.quantidade||0)}"><select class="ins-un"><option ${i.unidade==='kg'?'selected':''}>kg</option><option ${i.unidade==='g'?'selected':''}>g</option><option ${i.unidade==='litro'?'selected':''}>litro</option><option ${i.unidade==='unidade'?'selected':''}>unidade</option><option ${i.unidade==='ml'?'selected':''}>ml</option></select><input class="ins-custo" type="number" min="0" step="0.01" value="${Number(i.custoUnit||0)}" placeholder="Custo unit."><button type="button" class="icon-btn remove-ins"><i class="bi bi-trash"></i></button>`; el.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',calcular));el.querySelector('.remove-ins').onclick=()=>{el.remove();calcular()};insumos.appendChild(el);calcular();}
function calcular(){let total=0;document.querySelectorAll('.insumo-row').forEach(r=>{let q=Number(r.querySelector('.ins-qtd').value)||0,c=Number(r.querySelector('.ins-custo').value)||0,u=r.querySelector('.ins-un').value;if(u==='g'||u==='ml')q/=1000;total+=q*c});$('custoTotal').textContent=money(total);const rend=Number($('rendimentoFicha').value)||1;$('custoUnit').textContent=money(total/rend);return total;}
async function carregar(){try{const s=await getDocs(query(collection(db,'fichasTecnicas'),orderBy('produto')));fichas=s.docs.map(d=>({id:d.id,...d.data()}));render()}catch(e){console.error(e);lista.innerHTML='<tr><td colspan="6" class="empty">Não foi possível carregar as fichas.</td></tr>'}}
function render(){const t=$('buscaFicha').value.toLowerCase();const arr=fichas.filter(f=>!t||String(f.produto).toLowerCase().includes(t));lista.innerHTML=arr.length?arr.map(f=>{const n=(f.insumos||[]).length,total=Number(f.custoTotal||0),unit=total/(Number(f.rendimento)||1);return `<tr><td><strong>${esc(f.produto)}</strong></td><td>${Number(f.rendimento||0).toLocaleString('pt-BR')} ${esc(f.unidadeRendimento||'unidade')}</td><td>${n}</td><td>${money(total)}</td><td>${money(unit)}</td><td><button class="table-btn" data-edit="${f.id}"><i class="bi bi-pencil"></i></button><button class="table-btn danger" data-del="${f.id}"><i class="bi bi-trash"></i></button></td></tr>`}).join(''):'<tr><td colspan="6" class="empty">Nenhuma ficha cadastrada.</td></tr>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>abrir(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>excluir(b.dataset.del));}
function abrir(id=null){editId=id;$('tituloFicha').textContent=id?'Editar ficha técnica':'Nova ficha técnica';$('produtoFicha').value=id?(fichas.find(f=>f.id===id)?.produto||''):'';const f=id?fichas.find(x=>x.id===id):null;$('rendimentoFicha').value=f?.rendimento||1;$('unidadeFicha').value=f?.unidadeRendimento||'unidade';insumos.innerHTML='';(f?.insumos||[]).forEach(linha);if(!f)linha();calcular();modal.hidden=false;}
async function salvar(e){e.preventDefault();const produto=$('produtoFicha').value.trim();if(!produto){alert('Informe o produto.');return}const rendimento=Number($('rendimentoFicha').value);const listaIn=[...document.querySelectorAll('.insumo-row')].map(r=>({nome:r.querySelector('.ins-nome').value.trim(),quantidade:Number(r.querySelector('.ins-qtd').value)||0,unidade:r.querySelector('.ins-un').value,custoUnit:Number(r.querySelector('.ins-custo').value)||0})).filter(x=>x.nome&&x.quantidade>0);const custoTotal=calcular();const dados={produto,rendimento,unidadeRendimento:$('unidadeFicha').value,insumos:listaIn,custoTotal,custoUnitario:custoTotal/rendimento,atualizadoEm:serverTimestamp()};try{if(editId)await updateDoc(doc(db,'fichasTecnicas',editId),dados);else await addDoc(collection(db,'fichasTecnicas'),{...dados,criadoEm:serverTimestamp()});modal.hidden=true;await carregar()}catch(e){console.error(e);alert('Não foi possível salvar a ficha.')}}
async function excluir(id){if(!confirm('Excluir esta ficha técnica?'))return;try{await deleteDoc(doc(db,'fichasTecnicas',id));await carregar()}catch(e){alert('Não foi possível excluir a ficha.')}}
$('novaFicha').onclick=()=>abrir();$('addInsumo').onclick=()=>linha();$('fecharFicha').onclick=$('cancelarFicha').onclick=()=>modal.hidden=true;$('formFicha').onsubmit=salvar;$('rendimentoFicha').oninput=calcular;$('buscaFicha').oninput=render;modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true});carregar();
