import { db } from './firebase.js';
import { collection, getDocs } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const $=id=>document.getElementById(id); const br=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const num=v=>Number(v||0); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dt=v=>v?.toDate?v.toDate():v?.seconds?new Date(v.seconds*1000):v?new Date(v):null;
let data={comandas:[],vendas:[],delivery:[],movSaida:[],produtos:[]};
function operador(x){return x.operador||x.finalizadoPor||x.canceladaPor||x.usuarioNome||x.usuario||x.caixaOperador||'—'}
function tipo(x){return String(x.tipo||x.origemTipo||((x.peso!=null||x.produto)?'PESAGEM':'PROVISORIA')).toUpperCase()}
function dataRegistro(x){return x.canceladaEm||x.finalizadoEm||x.atualizadoEm||x.criadoEm||x.data||x.createdAt}
function dentro(v){const d=dt(v);if(!d)return false;const i=$('relInicio').value?new Date($('relInicio').value+'T00:00:00'):null;const f=$('relFim').value?new Date($('relFim').value+'T23:59:59.999'):null;return (!i||d>=i)&&(!f||d<=f)}
function localOrders(){try{return JSON.parse(localStorage.getItem('neoscale_delivery_orders')||'[]')}catch{return[]}}
async function carregar(){
 try{
  const [c,v,m,p]=await Promise.all([getDocs(collection(db,'comandas')),getDocs(collection(db,'vendasProdutos')),getDocs(collection(db,'estoqueMovimentos')),getDocs(collection(db,'produtos'))]);
  data.comandas=c.docs.map(d=>({id:d.id,...d.data()})); data.vendas=v.docs.map(d=>({id:d.id,...d.data()})); data.movSaida=m.docs.map(d=>({id:d.id,...d.data()})).filter(x=>['saida','SAIDA','saida_venda','saida-venda'].includes(String(x.tipo||''))); data.produtos=p.docs.map(d=>({id:d.id,...d.data()})); data.delivery=localOrders(); render();
 }catch(e){console.error(e);$('relConteudo').innerHTML='<div class="rel-empty-state">Não foi possível carregar os dados dos relatórios. Verifique as permissões do Firestore.</div>';}
}
function filtros(arr){const busca=$('relBusca').value.trim().toLowerCase();return arr.filter(x=>dentro(dataRegistro(x))&&(!busca||[x.numero,x.nome,x.produtoNome,x.produto,x.operador,x.pagamento,x.plataforma,x.origem,x.forma,x.tipo].map(v=>String(v||'').toLowerCase()).some(v=>v.includes(busca))))}
function kpis(items){$('relKpis').innerHTML=items.map(x=>`<div class="rel-kpi"><div class="rel-kpi-top"><span>${esc(x.label)}</span><div class="rel-kpi-icon"><i class="bi ${x.icon}"></i></div></div><strong>${esc(x.value)}</strong></div>`).join('')}
function titulo(t){$('relTitulo').textContent=t;$('periodoLabel').textContent=`Período: ${$('relInicio').value||'—'} até ${$('relFim').value||'—'}`;$('relStatusLabel').textContent=$('relTipo').selectedOptions[0].textContent}
function renderComandas(){const rows=filtros(data.comandas).filter(x=>{const s=x.status||'ABERTA';return ($('relStatus').value==='TODOS'||s===$('relStatus').value)&&($('relComandaTipo').value==='TODOS'||tipo(x)===$('relComandaTipo').value)});const fin=rows.filter(x=>x.status==='FINALIZADA'),can=rows.filter(x=>x.status==='CANCELADA'),valor=fin.reduce((s,x)=>s+num(x.total||x.valor),0);kpis([{label:'Total de comandas',value:rows.length,icon:'bi-receipt'},{label:'Finalizadas',value:fin.length,icon:'bi-check2-circle'},{label:'Canceladas',value:can.length,icon:'bi-x-circle'},{label:'Valor finalizado',value:br(valor),icon:'bi-cash-stack'}]);$('relConteudo').innerHTML=`<div class="rel-table-wrap"><table class="rel-table rel-comandas-table"><thead><tr><th>Comanda</th><th>Tipo</th><th>Status</th><th>Valor</th><th>Pagamento</th><th>Operador</th><th>Data / hora</th><th>Motivo</th></tr></thead><tbody>${rows.length?rows.map(x=>{const d=dt(dataRegistro(x));return `<tr><td><strong>#${esc(x.numero||'—')}</strong></td><td>${esc(tipo(x)==='PROVISORIA'?'PROVISÓRIA':tipo(x))}</td><td><span class="rel-badge ${x.status==='FINALIZADA'?'green':x.status==='CANCELADA'?'red':''}">${esc(x.status||'—')}</span></td><td class="rel-number">${br(x.total||x.valor)}</td><td>${esc(x.pagamento||'—')}</td><td>${esc(operador(x))}</td><td>${d?d.toLocaleString('pt-BR'):'—'}</td><td>${esc(x.motivoCancelamento||'—')}</td></tr>`}).join(''):`<tr><td colspan="8" class="rel-empty">Nenhuma comanda encontrada.</td></tr>`}</tbody></table></div>`;$('relRodape').textContent=`${rows.length} registro(s) encontrado(s) · Finalizadas: ${fin.length} · Canceladas: ${can.length}`}
function lojaRows(){return filtros(data.comandas).filter(x=>x.status==='FINALIZADA')}
function renderLoja(){const rows=lojaRows(),total=rows.reduce((s,x)=>s+num(x.total||x.valor),0),pag={};rows.forEach(x=>{const p=x.pagamento||'Outros';pag[p]=(pag[p]||0)+num(x.total||x.valor)});const top=Object.entries(pag).sort((a,b)=>b[1]-a[1]);kpis([{label:'Vendas da loja',value:rows.length,icon:'bi-shop'},{label:'Faturamento loja',value:br(total),icon:'bi-cash-stack'},{label:'Ticket médio',value:br(rows.length?total/rows.length:0),icon:'bi-graph-up-arrow'},{label:'Produtos / comandas',value:rows.length,icon:'bi-receipt'}]);$('relConteudo').innerHTML=`<div class="rel-summary-grid">${top.slice(0,6).map(([p,v])=>`<div class="rel-summary-box"><span>${esc(p)}</span><strong>${br(v)}</strong><div class="rel-bar"><i style="width:${total?Math.min(100,v/total*100):0}%"></i></div></div>`).join('')||'<div class="rel-empty-state">Nenhuma venda da loja no período.</div>'}</div><div class="rel-table-wrap"><table class="rel-table compact"><thead><tr><th>Comanda</th><th>Tipo</th><th>Operador</th><th>Pagamento</th><th>Data</th><th>Valor</th></tr></thead><tbody>${rows.map(x=>`<tr><td>#${esc(x.numero||'—')}</td><td>${esc(tipo(x))}</td><td>${esc(operador(x))}</td><td>${esc(x.pagamento||'—')}</td><td>${dt(dataRegistro(x))?.toLocaleString('pt-BR')||'—'}</td><td class="rel-number">${br(x.total||x.valor)}</td></tr>`).join('')||'<tr><td colspan="6" class="rel-empty">Nenhuma venda encontrada.</td></tr>'}</tbody><tfoot><tr class="rel-total-row"><td colspan="5">TOTAL</td><td class="rel-number">${br(total)}</td></tr></tfoot></table></div>`;$('relRodape').textContent=`${rows.length} venda(s) da loja · Total ${br(total)}`}
function deliveryRows(){return filtros(data.delivery).filter(x=>String(x.status||'').toUpperCase()!=='CANCELADO'&&String(x.status||'').toUpperCase()!=='CANCELADA')}
function renderDelivery(){const rows=deliveryRows(),total=rows.reduce((s,x)=>s+num(x.total||x.valor),0),plat={};rows.forEach(x=>{const p=x.plataforma||x.origem||'Balcão';plat[p]=(plat[p]||0)+num(x.total||x.valor)});kpis([{label:'Pedidos delivery',value:rows.length,icon:'bi-bicycle'},{label:'Faturamento delivery',value:br(total),icon:'bi-bag-check'},{label:'Ticket médio',value:br(rows.length?total/rows.length:0),icon:'bi-graph-up-arrow'},{label:'Plataformas',value:Object.keys(plat).length,icon:'bi-grid'}]);$('relConteudo').innerHTML=`<div class="rel-summary-grid">${Object.entries(plat).map(([p,v])=>`<div class="rel-summary-box"><span>${esc(p)}</span><strong>${br(v)}</strong><small>${total?((v/total)*100).toFixed(1):0}% do delivery</small></div>`).join('')||'<div class="rel-empty-state">Nenhuma venda delivery no período.</div>'}</div><div class="rel-table-wrap"><table class="rel-table compact"><thead><tr><th>Pedido</th><th>Plataforma</th><th>Pagamento</th><th>Status</th><th>Data</th><th>Valor</th></tr></thead><tbody>${rows.map(x=>`<tr><td>#${esc(x.numero||x.id||'—')}</td><td>${esc(x.plataforma||x.origem||'Balcão')}</td><td>${esc(x.pagamento||'—')}</td><td><span class="rel-badge green">${esc(x.status||'CONCLUÍDO')}</span></td><td>${dt(dataRegistro(x))?.toLocaleString('pt-BR')||'—'}</td><td class="rel-number">${br(x.total||x.valor)}</td></tr>`).join('')||'<tr><td colspan="6" class="rel-empty">Nenhum pedido encontrado.</td></tr>'}</tbody><tfoot><tr class="rel-total-row"><td colspan="5">TOTAL DELIVERY</td><td class="rel-number">${br(total)}</td></tr></tfoot></table></div>`;$('relRodape').textContent=`${rows.length} pedido(s) delivery · Total ${br(total)}`}
function renderFaturamento(){const loja=lojaRows(),del=deliveryRows(),vl=loja.reduce((s,x)=>s+num(x.total||x.valor),0),vd=del.reduce((s,x)=>s+num(x.total||x.valor),0),total=vl+vd;kpis([{label:'Faturamento total',value:br(total),icon:'bi-cash-coin'},{label:'Venda loja',value:br(vl),icon:'bi-shop'},{label:'Venda delivery',value:br(vd),icon:'bi-bicycle'},{label:'Participação delivery',value:`${total?(vd/total*100).toFixed(1):0}%`,icon:'bi-pie-chart'}]);$('relConteudo').innerHTML=`<div class="rel-summary-grid"><div class="rel-summary-box"><span>Loja</span><strong>${br(vl)}</strong><small>${total?(vl/total*100).toFixed(1):0}% do faturamento</small></div><div class="rel-summary-box"><span>Delivery</span><strong>${br(vd)}</strong><small>${total?(vd/total*100).toFixed(1):0}% do faturamento</small></div><div class="rel-summary-box"><span>Total</span><strong>${br(total)}</strong><small>${loja.length+del.length} vendas/pedidos</small></div></div><div class="rel-table-wrap"><table class="rel-table"><thead><tr><th>Origem</th><th>Quantidade</th><th>Faturamento</th><th>Ticket médio</th><th>Participação</th></tr></thead><tbody><tr><td><span class="rel-badge green">LOJA</span></td><td>${loja.length}</td><td class="rel-number">${br(vl)}</td><td class="rel-number">${br(loja.length?vl/loja.length:0)}</td><td>${total?(vl/total*100).toFixed(1):0}%</td></tr><tr><td><span class="rel-badge">DELIVERY</span></td><td>${del.length}</td><td class="rel-number">${br(vd)}</td><td class="rel-number">${br(del.length?vd/del.length:0)}</td><td>${total?(vd/total*100).toFixed(1):0}%</td></tr><tr class="rel-total-row"><td>TOTAL</td><td>${loja.length+del.length}</td><td class="rel-number">${br(total)}</td><td>—</td><td>100%</td></tr></tbody></table></div>`;$('relRodape').textContent=`Faturamento consolidado: ${br(total)} · Loja ${br(vl)} · Delivery ${br(vd)}`}
function renderSaida(){const rows=filtros(data.movSaida);const agrup={};rows.forEach(x=>{const nome=x.produtoNome||x.nome||x.produto||'Produto';const k=nome;agrup[k]??={nome,qtd:0,valor:0,unidade:x.unidade||x.unidadeMedida||x.tipoUnidade||''};agrup[k].qtd+=num(x.quantidade);agrup[k].valor+=num(x.valor||x.valorTotal||x.total)});const arr=Object.values(agrup).sort((a,b)=>b.qtd-a.qtd),qtd=arr.reduce((s,x)=>s+x.qtd,0),valor=arr.reduce((s,x)=>s+x.valor,0),kg=arr.filter(x=>String(x.unidade).toLowerCase().includes('kg')||String(x.unidade).toLowerCase()==='quilo').reduce((s,x)=>s+x.qtd,0);kpis([{label:'Itens com saída',value:arr.length,icon:'bi-box-arrow-up'},{label:'Quantidade total',value:qtd.toLocaleString('pt-BR'),icon:'bi-box-seam'},{label:'Saída em KG',value:kg.toLocaleString('pt-BR',{maximumFractionDigits:3})+' kg',icon:'bi-speedometer2'},{label:'Valor das saídas',value:br(valor),icon:'bi-cash-stack'}]);$('relConteudo').innerHTML=`<p class="rel-section-note">Relatório de saída de estoque. Produtos em KG são destacados pela unidade cadastrada; outras unidades permanecem como UN, L, ML etc.</p><div class="rel-table-wrap"><table class="rel-table compact"><thead><tr><th>Produto</th><th>Quantidade</th><th>Unidade</th><th>Valor</th></tr></thead><tbody>${arr.map(x=>`<tr><td><strong>${esc(x.nome)}</strong></td><td class="rel-number">${x.qtd.toLocaleString('pt-BR',{maximumFractionDigits:3})}</td><td>${esc(x.unidade||'—')}</td><td class="rel-number">${br(x.valor)}</td></tr>`).join('')||'<tr><td colspan="4" class="rel-empty">Nenhuma saída registrada no período.</td></tr>'}</tbody><tfoot><tr class="rel-total-row"><td>TOTAL</td><td class="rel-number">${qtd.toLocaleString('pt-BR',{maximumFractionDigits:3})}</td><td>—</td><td class="rel-number">${br(valor)}</td></tr></tfoot></table></div>`;$('relRodape').textContent=`${arr.length} produto(s) com saída · ${qtd.toLocaleString('pt-BR',{maximumFractionDigits:3})} unidade(s) · ${br(valor)}`}
function render(){const t=$('relTipo').value;$('statusField').style.display=t==='comandas'?'flex':'none';$('tipoField').style.display=t==='comandas'?'flex':'none';titulo($('relTipo').selectedOptions[0].textContent);if(t==='comandas')renderComandas();else if(t==='vendas-loja')renderLoja();else if(t==='vendas-delivery')renderDelivery();else if(t==='faturamento')renderFaturamento();else renderSaida()}
function defaults(){const n=new Date(),s=new Date(n.getFullYear(),n.getMonth(),n.getDate());$('relInicio').value=s.toISOString().slice(0,10);$('relFim').value=n.toISOString().slice(0,10)}
function exportar(){const t=$('relTipo').value;let linhas=[];if(t==='comandas')linhas=filtros(data.comandas).map(x=>[x.numero||'',tipo(x),x.status||'',num(x.total||x.valor).toFixed(2),x.pagamento||'',operador(x),dt(dataRegistro(x))?.toLocaleString('pt-BR')||'',x.motivoCancelamento||'']);else if(t==='vendas-loja')linhas=lojaRows().map(x=>[x.numero||'',tipo(x),operador(x),x.pagamento||'',num(x.total||x.valor).toFixed(2),dt(dataRegistro(x))?.toLocaleString('pt-BR')||'']);else if(t==='vendas-delivery')linhas=deliveryRows().map(x=>[x.numero||x.id||'',x.plataforma||x.origem||'Balcão',x.pagamento||'',x.status||'',num(x.total||x.valor).toFixed(2),dt(dataRegistro(x))?.toLocaleString('pt-BR')||'']);else if(t==='saida-produtos'){const a={};filtros(data.movSaida).forEach(x=>{const n=x.produtoNome||x.nome||x.produto||'Produto';a[n]??=[n,0,x.unidade||x.unidadeMedida||'',0];a[n][1]+=num(x.quantidade);a[n][3]+=num(x.valor||x.valorTotal||x.total)});linhas=Object.values(a)}else{const l=lojaRows(),d=deliveryRows(),vl=l.reduce((s,x)=>s+num(x.total||x.valor),0),vd=d.reduce((s,x)=>s+num(x.total||x.valor),0);linhas=[['LOJA',l.length,vl.toFixed(2)],['DELIVERY',d.length,vd.toFixed(2)],['TOTAL',l.length+d.length,(vl+vd).toFixed(2)]]}if(!linhas.length){alert('Não há dados para exportar.');return}const cab=t==='comandas'?['Comanda','Tipo','Status','Valor','Pagamento','Operador','Data/Hora','Motivo']:t==='vendas-loja'?['Comanda','Tipo','Operador','Pagamento','Valor','Data/Hora']:t==='vendas-delivery'?['Pedido','Plataforma','Pagamento','Status','Valor','Data/Hora']:t==='saida-produtos'?['Produto','Quantidade','Unidade','Valor']:['Origem','Quantidade','Faturamento'];const csv='\uFEFF'+[cab,...linhas].map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`relatorio-${t}-${$('relInicio').value}-${$('relFim').value}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('relAplicar').onclick=render;$('relHoje').onclick=()=>{defaults();render()};$('relBusca').oninput=render;$('relStatus').onchange=render;$('relComandaTipo').onchange=render;$('relTipo').onchange=render;$('relImprimir').onclick=()=>window.print();$('relExportar').onclick=exportar;defaults();carregar();
