import { db } from './firebase.js';
import { collection, query, orderBy, limit, onSnapshot, updateDoc, doc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
let pedidos=[]; let somAtivo=false; let audioCtx=null; let ultimoAlerta=''; let timerSom=null;
const $=id=>document.getElementById(id);
function dt(v){return v?.toDate?v.toDate():v?.seconds?new Date(v.seconds*1000):new Date(v||Date.now())}
function ativarSom(){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();somAtivo=true;$('btnSom').classList.add('active');$('btnSom').innerHTML='<i class="bi bi-volume-up-fill"></i> Som ativo';}catch(e){alert('Não foi possível ativar o áudio neste dispositivo.')}}
function beep(){if(!somAtivo||!audioCtx)return;const now=audioCtx.currentTime;const notas=[880,1175,880,1175];notas.forEach((freq,i)=>{const delay=i*.14;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='square';o.frequency.setValueAtTime(freq,now+delay);g.gain.setValueAtTime(.0001,now+delay);g.gain.exponentialRampToValueAtTime(.46,now+delay+.012);g.gain.exponentialRampToValueAtTime(.0001,now+delay+.10);o.connect(g);g.connect(audioCtx.destination);o.start(now+delay);o.stop(now+delay+.12)})}
function iniciarAlerta(){if(timerSom||!somAtivo)return;beep();timerSom=setInterval(beep,4000)} function pararAlerta(){if(timerSom){clearInterval(timerSom);timerSom=null}}
function card(x){const itens=(x.itens||[]).map(i=>`<div class="rep-card-item"><b>${i.quantidade}x</b><span>${i.nome}</span></div>`).join('');const proximo=x.status==='NOVO'?'PREPARO':x.status==='PREPARO'?'PRONTO':'ENTREGUE';const label=x.status==='NOVO'?'Aceitar e iniciar preparo':x.status==='PREPARO'?'Marcar como pronto':'Marcar como entregue';return `<article class="rep-ticket ${x.status==='NOVO'?'is-new':''}"><header><div><span class="rep-ticket-label">${x.status==='NOVO'?'NOVA SOLICITAÇÃO':'REPOSIÇÃO'}</span><h3>${x.local||'Buffet'}</h3></div><time>${dt(x.criadoEm).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></header><div class="rep-ticket-items">${itens}</div><button class="rep-action" data-id="${x.id}" data-next="${proximo}">${label}</button></article>`}
function render(){const grupos={NOVO:[],PREPARO:[],PRONTO:[]};pedidos.forEach(x=>{if(grupos[x.status])grupos[x.status].push(x)});[['NOVO','listaNovo','countNovo'],['PREPARO','listaPreparo','countPreparo'],['PRONTO','listaPronto','countPronto']].forEach(([s,l,c])=>{$(l).innerHTML=grupos[s].map(card).join('')||'<div class="rep-empty">Nenhuma solicitação nesta etapa.</div>';$(c).textContent=grupos[s].length});$('kpiNovos').textContent=grupos.NOVO.length;$('kpiPreparo').textContent=grupos.PREPARO.length;$('kpiProntos').textContent=grupos.PRONTO.length;if(grupos.NOVO.length){if(ultimoAlerta!==grupos.NOVO.map(x=>x.id).join(',')){ultimoAlerta=grupos.NOVO.map(x=>x.id).join(',');iniciarAlerta()}}else{ultimoAlerta='';pararAlerta()}}
$('btnSom').addEventListener('click',()=>{ativarSom();if(pedidos.some(x=>x.status==='NOVO'))iniciarAlerta()});document.addEventListener('click',async e=>{const b=e.target.closest('[data-id][data-next]');if(!b)return;try{pararAlerta();await updateDoc(doc(db,'reposicoesBuffet',b.dataset.id),{status:b.dataset.next,atualizadoEm:serverTimestamp()})}catch(err){console.error(err);alert('Não foi possível atualizar a solicitação.')}});
const q=query(collection(db,'reposicoesBuffet'),orderBy('criadoEm','desc'),limit(100));onSnapshot(q,s=>{pedidos=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.status&&x.status!=='ENTREGUE');render()},e=>{console.error(e);$('listaNovo').innerHTML='<div class="rep-empty">Não foi possível carregar as solicitações.</div>'});
